### PR TITLE
[WIP] Integrate Fzy.

### PR DESCRIPTION
**Pull request by CrossR**
Currently just a test of the whole path (`esy`->`reason`->Here).

Need to sort out:
  - [X] Build on Windows.
  - [x] Why I can't use the returned `choices`.
  - [x] Tidy up the interface. When the returning works, it will just be stuff for the matching items. Should that be padded back to add every item with a score of 0 and no positions? Should that be left up to the consumer?

### CODE REVIEW

**Comment by CrossR** [comment]
Okay, the `esy-fzy` issue is due to a missing header file that `mingw` doesn't seem to have: `termios.h`.

I could just strip out all the `tty` related bits really, though there is a second part that is also missing (`c->worker_count = (int)sysconf(_SC_NPROCESSORS_ONLN);`). I could either remove that, or perhaps update it to have a working windows equivalent to get the number of cores.

EDIT: Went with the second option: Stripped out the tty bits, added a Windows specific part to get the core number. Still getting build issues when trying to use it on Windows due to `pthreads`...

**Comment by CrossR** [comment]
Could perhaps do with a hand with the C-bindings over in https://github.com/CrossR/reason-fzy/blob/master/src/bindings.c#L14.

I assume I'm just using the wrong style of way of passing data back to OCaml/Reason. Though I'm surprised it also fails with just a string/double, which implies I'm probably missing something larger 😅 .

I figure either an `array(Result.t)` or a `Result.t` (which contains arrays) is best, and the first seemed easier, but currently it seems to just stop executing the second I try to access the returned data. Is it something you could lend a hand with @bryphe? I was struggling to find examples of returning an array as part of an obj, so I think I'm just going about it the wrong way and using the wrong style of storing stuff.

**Comment by bryphe** [comment]
Wow, looks like we're getting really close! Thanks for the work on this, @CrossR !

I noticed an issue with the bindings - I think it needs to be:
```
Store_field(v, 0, caml_copy_string(matchTerm));
Store_field(v, 1, caml_copy_double(score));
```
instead of:
```
Store_field(v, 0, String_val(matchTerm));
Store_double_field(v, 1, score);
```

The `caml_copy_string` is needed for strings, so that they get copied into a boxed value for the OCaml GC. And same for floats/doubles - I believe `Store_double_field` is only for the special case of a floating point array (where OCaml stores them unboxed: https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html) - but in the general case, they need to be copied (boxed).

With that change - I got through the first test case, it seemed (the test case though expected 2 items - but it seems like with the latest update there'd only be one item, with a score of 2.815) - I updated that case as: 
```
  test("Test fuzzy on basic test", ({expect}) => {
    let testString = "SRC";
    let testList = [|"browser/src/index.ts", "browser/SRC/index.ts"|];

    prerr_endline ("BEFORE");
    let score = Fzy.searchForItem(testList, testString);
    prerr_endline ("AFTER");

    expect.int(Array.length(score)).toBe(1);
    expect.float(score[0].score).toBeCloseTo(2.815);
    expect.string(score[0].term).toEqual("browser/SRC/index.ts");
    //expect.float(score[1].score).toBeCloseTo(0.0);
  });
```

 But the second test case seemed to hang at the `choices_search` method:
```
    printf("Needle: %s\n", needle);
    choices_search(&choices, needle);
    printf("Done choices search\n");
```
I tried limiting the results by capping the `nItems` - but it still hung (was testing on OSX). I'm not sure what was different between the first and second test case; but it might need some additional logging inside the `choices_search` to see exactly where it is failing.

Hope that helps get the first test unblocked, at least!

Also in case it helps... here's the full `fzy_search_for_item` I was testing with (extra logging, capped items):
```
CAMLprim value fzy_search_for_item(value vHaystack, value vNeedle) {
    CAMLparam2(vHaystack, vNeedle);
    CAMLlocal2(v, ret);

    fprintf(stderr, "FUZZY SEARCH TEST\n");

    options_t options;
    choices_t choices;
    options_init(&options);
    choices_init(&choices, &options);

    int nItems = Wosize_val(vHaystack);
    
    // Cap the number of items, just to rule out the search taking a long time...
    if (nItems > 25) {
        nItems = 25;
    }
    printf("Items passed in: %d\n", nItems);

    for (int i = 0; i < nItems /*nItems*/; ++i) {
        const char* add = String_val(Field(vHaystack, i));
        printf("Adding: %s\n", add);
        choices_add(&choices, add);
    }

    printf("Done adding!\n");

    const char *needle = String_val(vNeedle);
    printf("Needle: %s\n", needle);
    choices_search(&choices, needle);
    printf("Done choices search\n");

    int count = choices_available(&choices);
    printf("COUNT: %d", count);
    ret = caml_alloc(count, 0);

    // Fzy only stores scores for those with an actual match.
    for (int i = 0; i < count; ++i) {

        // Get the search terms that actually matched.
        const char *matchTerm = choices_get(&choices, i);
        
        // Now go back and get the score again, and populate the
        // match locations.
        int n = strlen(matchTerm) + 1;
        size_t positions[n];
        for (int i = 0; i < n; i++)
          positions[i] = -1;

        const double score = match_positions(needle, matchTerm, &positions[0]);

        printf("STArting alloc....\n");
        v = caml_alloc(2, 0);

        printf("Starting stores....\n");
        printf("matchTerm: %s\n", matchTerm);
        Store_field(v, 0, caml_copy_string(matchTerm));
        Store_field(v, 1, caml_copy_double(score));
        // Store_field(v, 2, Double_val(positions));

        printf("Starting store to ret....\n");
        Store_field(ret, i, v);
    }

    choices_destroy(&choices);

    printf("Returning....\n");
    CAMLreturn(ret);
}
```

**Comment by CrossR** [comment]
Thanks for the help!

Swapping to the `Store_field` and updating the tests allows it to work now, for the basic/Oni2/Linux tests for me now. Not sure why you were getting crashes...I'll investigate that a bit further in once I've got stuff stable enough to setup a bunch of different CI options. Quick tests on Windows 10 and Catalina worked, so its stable enough to continue getting the basics sorted.

Now I just need to pass the positions and work out what I think the best interface for this is (return just matches or return everything).

EDIT: Returning positions works now, and I can pass every test locally on my Mac and Windows machines. It looks like the CI is seeing what you see though, so need to do a clean build and start debugging from there.

**Comment by CrossR** [comment]
Got bunch more tests added, and am now working on the build issues again.

Mac is getting `pthread_join: Undefined error: 0` which causes it to fail. Luckily I can repro that locally now, so going to work on that. The Linux error seems similar, but it fails during the build. Hopefully its the same fix for each.

The missing cache is a pain since this takes so long to build, so I'm still not sure if the Windows CI is happy or not yet. Locally I have every test running on Windows at least.

EDIT: Looks like that was the cause of the mac failure, when you run a big test and it attempted to spin up threads, the way I was getting the core count wasn't working as expected. This would set the worker number to something undefined and cause issues. I've moved that logic out of `esy-fzy` for now, since it didn't want to work there. Setting it up as part of the `options` struct to init the `choices` works just as well for now.

**Comment by CrossR** [comment]
For my own reference:

3 issues were causing build / CI failures:

 - Building with esy 0.5.6 meant Windows wasn't compiling as it couldn't find the `ar` command. Updating to 0.5.8 fixed that.
 - Mac was hitting an issue of not being able to calc the correct thread number.
 - Linux was not compiling correctly. I think it was due to `lpthreads` vs `pthreads`? This could have caused the Mac issue too, but I'm doubtful.

With those 3 fixes done, CI here is finally green! Just need to actually package up `fzy` now, and add it to `reasonFuzz` then update the tests to use the new interface rather than the lib directly.

**Comment by bryphe** [comment]
> With those 3 fixes done, CI here is finally green! Just need to actually package up fzy now, and add it to reasonFuzz then update the tests to use the new interface rather than the lib directly.

Woah! Awesome @CrossR ! Nice find on those 3 issues. Can't wait to get this hooked up into Onivim 2- the perf difference is pretty incredible

**Pull request merged**
